[package]
name = "mrust_codegen"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
syn = { version = "^1.0", features = ["full", "fold"] }
quote = "^1.0"
